# Generated by Django 6.0.6 on 2026-07-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['create_time']},
        ),
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
