# Generated by Django 6.0.6 on 2026-07-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['create_time'], 'verbose_name': 'AboutUs Requests', 'verbose_name_plural': 'AboutUs Requests'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['create_time'], 'verbose_name': 'ContacUs Forms', 'verbose_name_plural': 'ContacUs Forms'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['create_time'], 'verbose_name': "Note's", 'verbose_name_plural': "Note's"},
        ),
    ]
